### PR TITLE
#696: added ability to select calendars to be sent to watch

### PR DESCRIPTION
**Pull request by rain-bipper**

### CODE REVIEW

**Comment by rain-bipper** [comment]
For now the calendar choosing button is disabled, if there was no permission granted. The logic of permission requesting remained the same.
Also I think it is not responsability of information query method to make permission request. It up to client.

**Comment by fcaronte** [comment]
I try this but I get FC. Is working for you? Need some special thing to do?

**Comment by rain-bipper** [comment]
It is works perfectly for me: Xiaomi A1, Android 9, Amazfit Pace. No special things to do is necessary. 
Can you post the stack of FC?

**Comment by fcaronte** [comment]
I test fastly and then removed to work to chime and other things, but i got this (maybe i do something wrong during test, i will check better when i can)
49fa5b0e-c143-4c4a-9d33-7f140159979b

**Comment by rain-bipper** [comment]
Oh, it's really looks like problem in my code. I'll fix it. Thank you

**Comment by rain-bipper** [comment]
@fcaronte 
Ok,  I've fixed the FC. Please check it

Steps to reproduce the error before fix:
1. fresh install or data clean of AmazMod
2. grant calendar permission
3. open (or reopen, if exist) "GreatFit / calendar" settings window

**Comment by fcaronte** [comment]
Ok but I can try next week or maybe on weekends

**Comment by GreatApo** [comment]
I just tested this. I show no bugs and it worked as expected. It will undergo more testing in the dev branch.

Thank you! We are expecting more :P

**Pull request merged**
